###############################################################################
# Board Configuration
###############################################################################
esphome:
  name: ${device_internal_name}
  friendly_name: ${device_friendly_name}

###############################################################################
# Enable logging
###############################################################################
logger:

###############################################################################
# Enable logging
###############################################################################
api:
  id: ${device_internal_name}_ha_api
  encryption:
    key: !secret api_encryption_key
  reboot_timeout: 0s

###############################################################################
# OTA Settings
###############################################################################
ota:
  platform: esphome
  password: !secret ota_password

safe_mode:
  disabled: false
  reboot_timeout: 10min
  num_attempts: 5

###############################################################################
# Network Settings
###############################################################################
# Ensure mDNS is enabled
mdns:
  disabled: false

# Disable IPV6
network:
  enable_ipv6: False

###############################################################################
# Binary Sensors
###############################################################################
binary_sensor:
  # ESP Status Sensor
  - platform: status
    id: ${device_internal_name}_status

###############################################################################
# Sensors
###############################################################################
sensor:
  # Human Readable Uptime Conversion Sensor
  - platform: uptime
    id: ${device_internal_name}_uptime_sensor
    name: "Uptime Sensor"
    update_interval: ${device_sampling_time}
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device_internal_name}_uptime_human
            state: !lambda |-
              int seconds = round(id(${device_internal_name}_uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

###############################################################################
# Text Sensors
###############################################################################
text_sensor:
  # ESPHome Version Sensor
  - platform: version
    id: ${device_internal_name}_version
    name: "ESPHome Version"
    disabled_by_default: true
  # Expose Uptime human readable
  - platform: template
    name: Wemos Barn Uptime
    id: ${device_internal_name}_uptime_human
    icon: mdi:clock-start

###############################################################################
# Switch
###############################################################################
switch:
  # Soft Restart the device
  - platform: restart
    id: ${device_internal_name}_device_restart
    name: "Restart"

  # Restart the device in Safe Mode
  - platform: safe_mode
    id: ${device_internal_name}_device_safe_mode
    name: "Use Safe Mode"
